### ISSUE TITLE
Option to turn off window transparency

### ISSUE THREAD

**Issue by nbb1967** [BLumia/pineapple-pictures#104]
Feature request: Option to turn off window transparency.
Window transparency is probably useful in some use cases, but when viewing images with transparency (PNG, SVG...), the desktop is visible through them.

**Comment by BLumia** [comment]
The checkerboard feature is intended to address the original issue, but if you want a non-transparent variant of this app, consider try this fork instead:

- https://github.com/yyc12345/pineapple-pictures/releases/tag/0.8.1
