### ISSUE TITLE
Scaling the transparent background

### ISSUE THREAD

**Issue by nbb1967** [BLumia/pineapple-pictures#107]
Currently, when scaling an image, the transparent background (gray-white grid) is also scaled. Is this a bug or a feature?

**Comment by BLumia** [comment]
It's intended since the grid is fixed size so user could use the grid as an object of reference to determine the size of the image while scaling.

btw, if you hold the <kbd>shift<kbd> key and click the grid button, the grid will be in a lighter color. Just in case you might need this.
