### ISSUE TITLE
any plan to support .jxl?

### ISSUE THREAD

**Issue by ferstar** [BLumia/pineapple-pictures#118]

**Comment by BLumia** [comment]
Well, it's already supported if you're using Linux or build from source. All you need to do is install (or build) [`kimageformats`](https://api.kde.org/frameworks/kimageformats/html/index.html), which is available in most Linux distros and even MSYS2 for Windows.

If you are using Windows binary that I provided in the GitHub Release page, then I haven't start shipping JXL support yet. The things need to be done is simply build the JXL library in my CI build script, similar to https://github.com/BLumia/pineapple-pictures/issues/99 but for HEIC.

**Comment by BLumia** [comment]
Related progress:

Now I'm tweaking the Windows MSVC CI build to ensure it is built with Qt 6 and ship binary artifacts after the build is finished. Then we can reuse existing imageformats binaries to support JXL and other formats like RAW and HEIC. You can already do that by grabing the CI artifacts and download [kimageformats binaries provided by jurplel](https://github.com/jurplel/kimageformats-binaries/releases). See also: https://github.com/BLumia/pineapple-pictures/issues/99#issuecomment-2211695466

**Comment by ferstar** [comment]
Well, I just installed `kimageformats`, and everything works perfectly!

![image](https://github.com/BLumia/pineapple-pictures/assets/2854276/a34b068e-863f-4732-99cf-141ce72e7bca)

![image](https://github.com/BLumia/pineapple-pictures/assets/2854276/01f9721d-cf92-4370-8f7d-eb7889c7ffa4)


Sorry for the late reply :-)
