### ISSUE TITLE
pineapple-pictures v0.8.0 fails to build on i386

### ISSUE THREAD

**Issue by sudipm-mukherjee** [BLumia/pineapple-pictures#122]
I updated pineapple-pictures in Debian today to v0.8.0 but it fails to build for i386. The previous v0.7.4 did not have the build failure.

The build log of v0.8.0 for i386 can be seen at `https://buildd.debian.org/status/fetch.php?pkg=pineapple-pictures&arch=i386&ver=0.8.0-1&stamp=1722081327&raw=0`

I will be happy to give any extra log or test any patch if needed.

**Comment by BLumia** [comment]
```
/usr/include/i386-linux-gnu/qt6/QtCore/qfloat16.h: In member function ‘constexpr qfloat16::operator NativeType() const’:
/usr/include/i386-linux-gnu/qt6/QtCore/qfloat16.h:64:52: error: SSE register return with SSE2 disabled
   64 |     constexpr operator NativeType() const noexcept { return nf; }
      |                                                    ^
/usr/include/i386-linux-gnu/qt6/QtCore/qfloat16.h: In function ‘qfloat16 operator+(qfloat16, qfloat16)’:
/usr/include/i386-linux-gnu/qt6/QtCore/qfloat16.h:124:147: error: operation not permitted on type ‘_Float16’ without option ‘-msse2’
  124 |     friend inline qfloat16 operator+(qfloat16 a, qfloat16 b) noexcept { return qfloat16(static_cast<NearestFloat>(a) + static_cast<NearestFloat>(b)); }
      |  
```

I guess it's very likely a Qt6 issue or `SSE2` support issue? Since according to the log that you provided, it's unlikely related to Pineapple Pictures itself.

**Comment by sudipm-mukherjee** [comment]
Yeah, seems like you are correct. I ran a pipeline with 0.7.4 on i386 and that now fails. So, something else has changed. I will look more into it. Thanks a lot for the quick reply and support.

**Comment by sudipm-mukherjee** [comment]
Closing this issue as this has been seen on other packages also and  https://codereview.qt-project.org/c/qt/qtbase/+/579205 has been opened.
