### ISSUE TITLE
Esc Space shortcut for exit

### ISSUE THREAD

**Issue by sonichy** [BLumia/pineapple-pictures#128]
叫你取消你肯定不肯，给一个设置禁用可以吗？

**Comment by BLumia** [comment]
如果你这个需求是打算提完给自己用的话，你自己改下代码自己用就是了。改法都告诉你，直接删掉这四行：

https://github.com/BLumia/pineapple-pictures/blob/5d2ddc199abbc0072243b95d29e0cd78e2251857/app/actionmanager.cpp#L152-L155

> 叫你取消你肯定不肯

你还真猜错了。我的原计划其实是做自定义快捷键（允许设置/修改所有 action 的快捷键），如果搞了的话显然用户是可以自己把退出的快捷键改掉的。

但是，短时间内没空搞，所以如果你这个需求不只是给你自己提的话，就只能等我有空搞这个了（

**Comment by sonichy** [comment]
那先把退出快捷键取消了吧，或者用组合键盘(Alt+Q)，快捷键要在帮助里说明。

**Comment by BLumia** [comment]
你如果是自己的需求就自己改代码后编译。在我去做快捷键支持之前，我无计划删/改快捷键。

现有的快捷键列表请参见 Wiki： https://github.com/BLumia/pineapple-pictures/wiki/Shortcuts

**Comment by sonichy** [comment]
快捷键当然要写到软件里面啦
https://s21.ax1x.com/2024/10/19/pAUTixe.png
