### ISSUE TITLE
总在最前无法记忆

### ISSUE THREAD

**Issue by sonichy** [BLumia/pineapple-pictures#130]
取消总在最前，关闭再打开，仍然是总在最前。

**Comment by BLumia** [comment]
你是在设置里调的选项么？只有设置里是“默认行为”，右键菜单是临时行为。

**Comment by sonichy** [comment]
设置里没有总在最前。
右键是临时行为的设计不科学。

**Comment by BLumia** [comment]
> 设置里没有总在最前。

？？你版本是什么？这个选项应该是设置对话框刚有的时候就加了的。

请提供设置对话框的截图。

**Comment by BLumia** [comment]
无法复现问题，缺少复现问题的必要信息且汇报人未提供，关闭处理。

**Comment by sonichy** [comment]
设置里 [总在最前] 在第一行，是我没看到。
