### ISSUE TITLE
smooth image filter (by default)

### ISSUE THREAD

**Issue by Seryi3** [BLumia/pineapple-pictures#19]

**Comment by BLumia** [comment]
It's intended to make people see the pixels clearly when zoom-in, so it will never be the default option. If you are seeing pixels, it's "pixelmap", I actually cannot understand why other image viewers do smooth images when zoomed-in, then the user will get a pretty blurred image and won't be able to count pixels when needed.

You can edit [here](https://github.com/BLumia/pineapple-pictures/blob/dc17e1d0b1045730584ece4e433f058c5d0c1830/app/graphicsview.cpp#L316) if you'd like to view image smoothed when zoomed-in.
