### ISSUE TITLE
webp images are not added to the image queue and do not have a properties menu

### ISSUE THREAD

**Issue by Seryi3** [BLumia/pineapple-pictures#25]
*edit by maintainer:*

 - [x] added to the image queue
 - [x] have a properties menu

**Comment by BLumia** [comment]
Hi, it's a known issue and planned to be fixed within the next release. If you need a quick fix, you can just edit the following place and add the file suffix you needed to the code, and it will work then.

https://github.com/BLumia/pineapple-pictures/blob/2b5119414371c0216a5c2a86db3bf80b0abef33d/app/mainwindow.cpp#L229

It's just a workaround solution though, the later updates may consider no longer use hard-coded formats list or other solution.

**Comment by BLumia** [comment]
- [ ] added to the image queue
 - [x] have a properties menu

The last commit adds the ability to show property dialog to any supported formats. You can get a pre-built binary from [here](https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/37679423/artifacts).

**Comment by BLumia** [comment]
*webp* images will now be added to the image queue after https://github.com/BLumia/pineapple-pictures/commit/9c460f2eded905af41f734dfddc7ffd85376378d. You can get a pre-built binary from [here](https://ci.appveyor.com/project/BLumia/pineapplepictures/builds/37953544).

Please notice I still haven't introduced a way to customize this behavior, so even if we support formats like AVIF and etc, it still won't load into the image queue. This might be a configurable option but no promise for now.
