### ISSUE TITLE
无法打开图片Size比较大的图片

### ISSUE THREAD

**Issue by Jasonluo925** [BLumia/pineapple-pictures#28]
这边做了一个拼图 （Size： 282M 和 2G 的图片）
Format： JPG
Resolution: 24480x49152  96dpi   24bit
Size比较大的图片都不能打开， 软件显示 “图像数据无效或暂未支持”

软件版本：0.4.2-0-gdeed477
操作系统： Win10

**Comment by BLumia** [comment]
请问方便提供原始图像文件或可复现问题的有效图像文件的生成方式以便测试吗？

282M 不至于打不开，2G 的或许是因为我提供的预编译版本是 32 位版本（原因是方便直接兼容 ARM Windows 设备）。如果 282M 的确实打不开，希望您可以提供原始图像文件或生成方式以便这边进一步定位。

**Comment by BLumia** [comment]
已能复现，使用 Affinity Photo 1.9.0.932 创建的 24480x49152 px 96dpi RGB/8 导出 Jpeg 图像可直接复现问题。见附件。

[GH-28.zip](https://github.com/BLumia/pineapple-pictures/files/6175679/GH-28.zip)

待进一步定位。

**Comment by BLumia** [comment]
本机编译的 64 位版本可以正常打开，目前猜测还是默认提供的预编译版本是 32 位的问题，自己构建 64 位版本应该就可以。不知道你这边是否方便自己编译 64 位版本。

我这边暂时提供一个开发环境（MSYS 2，MinGW x64 工具链）下的构建可供测试问题，下面三个压缩包在同一目录下解压即可测试。

注意：下面的压缩包对应的测试版本仅供测试。为了方便，EXIF 属性信息的支持未包含在内，也仅提供了 JPEG 图像格式所需的必要动态链接库文件。

[x64-testbuild-6a9e5e8-1.zip](https://github.com/BLumia/pineapple-pictures/files/6175785/x64-testbuild-6a9e5e8-1.zip)
[x64-testbuild-6a9e5e8-2.zip](https://github.com/BLumia/pineapple-pictures/files/6175791/x64-testbuild-6a9e5e8-2.zip)
[x64-testbuild-6a9e5e8-3.zip](https://github.com/BLumia/pineapple-pictures/files/6175796/x64-testbuild-6a9e5e8-3.zip)

**Comment by BLumia** [comment]
24480x49152x24bit （完全载入需 3.3618 GiB）确实超出了 32 位支持的图像大小，在做专门的超大分辨率文件支持之前，切换到 64 位即可解决无法打开的问题，尽管打开仍然会需要卡一小会儿。

下次发布会切换到只提供 64 位预编译版本。自 https://github.com/BLumia/pineapple-pictures/commit/cd94f1a84cd725571fe4988f30005f4fb0695440 后 CI 也将切换为默认构建 64 位版本，目前也可以在 AppVeyor 获取到 CI 构建的版本。

如有其它问题请补充回复。
