### ISSUE TITLE
Images are pixelated when zoomed out

### ISSUE THREAD

**Issue by 33kk** [BLumia/pineapple-pictures#31]
![Screenshot](https://i.kkx.one/cfkketoa.png)

top: pineapple-pictures
botton: gwenview

**Comment by BLumia** [comment]
https://github.com/BLumia/pineapple-pictures/blob/4c07a89ca3a8a9bec39c3ff3bc984849ef218bf5/app/graphicsview.cpp#L392-L399

Currently pineapple-pictures uses [`QGraphicsPixmapItem::setTransformationMode`](https://doc.qt.io/qt-5/qgraphicspixmapitem.html#setTransformationMode) with `SmoothTransformation ` to smooth image when zoomed out, not sure how Gwenview did, will investigate it later™.

By the way, did you mind share the original image so I can use that to test on my machine?

Thanks!

**Comment by 33kk** [comment]
Can't give that image right now, any image should work. I feel like there's some other transformation going on, since it looks fine in flameshot recent uploads window, which uses QLabel with scaled QPixmap

**Comment by BLumia** [comment]
https://github.com/KDE/gwenview/blob/d82258c4318188993a428f51e4a205083a121602/lib/documentview/rasterimageitem.cpp#L120

I don't have an image that very suited for testing this issue right now. It *seems* like Gwenview uses the same method (not 100% sure, just did a quick look), may look into it later. It could be an interesting issue if Gwenview really does that and the behavior is not the same :p

**Comment by BLumia** [comment]
Just randomly drew an ellipse and seems I'm able to reproduce this issue.

![Screenshot](https://user-images.githubusercontent.com/10095765/122165948-891c6100-ceab-11eb-821b-5b3c7680eb57.png)

[Original image used to test this bug](https://user-images.githubusercontent.com/10095765/122166062-a6512f80-ceab-11eb-88a5-9cd4c41a328b.png)

Anyway, I'll investigate it later™.

**Comment by BLumia** [comment]
I'm probably using the QGraphicsView/QGraphicScene in a wrong way. Currently, when zooming in and out, the program will apply the scale to the graphics view instead of the image (QGraphicsPixmapItem) item. The `SmoothTransformation` mode applied to the item seems will only work when the scale transform is applied to the item.

Maybe I need to refactor some part of the code to resolve this issue, still not sure about this. Any confirmed this issue and this should be resolved in later updates.

**Comment by BLumia** [comment]
Hi and could you try if https://github.com/BLumia/pineapple-pictures/commit/36c54addce2f7ba34f43631276ca4ad901b5dc36 resolved this issue?

**Comment by 33kk** [comment]
Looks good now, thanks <img src="https://cdn.betterttv.net/emote/5ec059009af1ea16863b2dec/3x" height="40">

Preview thing is also not using SmoothTransform btw
![Screenshot](https://i.kkx.one/d9ja9upp.png)

**Comment by BLumia** [comment]
> Preview thing is also not using SmoothTransform btw
> ![Screenshot](https://camo.githubusercontent.com/dfe564d67deaff160c745de537be2eb1e7c83551a7898de77026511f1c4b829e/68747470733a2f2f692e6b6b782e6f6e652f64396a61397570702e706e67)

The preview and the main area share the same graphics scene so only one of them could look smooth in the current implementation. It's just a navigation preview so I guess it's okay ;P

I'll close this issue then, let me know if you found any other issue :)

**Comment by BLumia** [comment]
Update: 36c54ad introduced a bug that has been fixed in 7a0ed5b. If you are using 36c54ad please consider update :)
