### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [BLumia/pineapple-pictures#36]
Currently (as of version [0.5.2](https://github.com/BLumia/pineapple-pictures/releases/tag/0.5.2)) [Pineapple Pictures](https://github.com/BLumia/pineapple-pictures) saves it few settings in AppData:

`C:\Users\User\AppData\Local\Pineapple Pictures\config.ini`

My suggestion- when **Pineapple Pictures** starts it checks its program folder (where is the executable- **ppic.exe**) for configuration file (**config.ini**) and if it is there the program should use it loading settings from it and saving settings to it, not writing to AppData. Thus the program would be fully and truly portable not writing outside of its folder so that the users would be able to carry it on an USB stick or on an external hard drive with its settings.

Portable mode offers several advantages:

- **backup** - portable programs can be easily backed up on external drives in case disaster strikes- hardware failure or OS failure;
- **mobility** - portable programs can be easily transferred from machine to machine with all their data and settings;
- **testing** - portable mode facilitate testing- one can test different versions (stable, alpha, beta) with different settings or even use multiple instances of one and the same version with different settigs since settings are isolated;

I suppose that this feature will be easy to be implemented.

**Comment by BLumia** [comment]
Hi, it already has a portable mode! Please refer to [Portable Mode on the repo Wiki](https://github.com/BLumia/pineapple-pictures/wiki/Portable-Mode), and let me know if you got any question about portable mode :)
