### ISSUE TITLE
删除照片功能建议

### ISSUE THREAD

**Issue by mysalter** [BLumia/pineapple-pictures#42]
在看图的时候能够加入delete直接删除照片的功能

**Comment by BLumia** [comment]
目前的设计是希望尽可能避免误操作原始图片文件的，所以其实也不希望一键就能删掉图片，按 delete 弹出提示，确认后放到回收站可能更合理一些。

这个需求暂时放到这里看看是不是有更多人会用到好了。

**Comment by BLumia** [comment]
最近发现确实偶尔会有这样的需求，添加了这个功能。目前行为：按下删除键会弹出对话框，询问是否删除到回收站。确认后会删除到回收站。

目前 master 分支包含了这个特性，预计包含这个功能的版本是 0.8.0（当前最新 tag 是 0.7.4）。
