### ISSUE TITLE
If the transparency of the background can be adjusted will be even better

### ISSUE THREAD

**Issue by xmuli** [BLumia/pineapple-pictures#49]
Feel good, can you add an option to set a default background transparency?
And how should I set it as the default viewer 🥰?  (I didn't find it, or I can't set it as the default software directly?)

**Comment by BLumia** [comment]
> Feel good, can you add an option to set a default background transparency?

Currently no plan to introduce the option to adjust background transparency (maybe in the future but no promise), if you are viewing a black image with an alpha channel that the default dark background can cause trouble with, try holding Shift and click the checkerboard icon. and just FYI you can change the background transparency here if you plan to compile it by yourself :)

https://github.com/BLumia/pineapple-pictures/blob/00168a34f0b19415051193b55954fc8f6b742af8/app/graphicsview.cpp#L27

> And how should I set it as the default viewer? (I didn't find it, or I can't set it as the default software directly?)

I'm not sure which OS you're using. For generic Linux desktop environments the `net.blumia.pineapple-pictures.desktop` file should already contain a list of known supported formats/mimetypes. For Windows you can only associated file types manually for now (#13).

**Comment by xmuli** [comment]
>  setStyleSheet("background-color: rgba(0, 0, 0, 220);" 

thanks

> I'm not sure which OS you're using. For generic Linux desktop environments the net.blumia.pineapple-pictures.desktop file should already contain a list of known supported formats/mimetypes. For Windows you can only associated file types manually for now (#13).

I tried the portable version, but win10 can't specify it as the default open software.

emmm， win10 20H1🤣，I have used "Inno Setup" package to create the installer, it is very convenient, you can try it.   see: [link](https://www.cnblogs.com/linuxAndMcu/p/10974927.html)

**Comment by BLumia** [comment]
> I tried the portable version, but win10 can't specify it as the default open software.

You can only associate it manually. Image quoted from somewhere else:

![image](https://user-images.githubusercontent.com/10095765/151658089-c1701a59-f131-4446-bb58-6c7f7fe72042.png)

Select "Choose another app", then add this application to this list and select it as the default app. I know it's complex but it's the only way to do the association work before a proper solution comes out.

> I have used "Inno Setup" package to create the installer, it is very convenient

Thanks for the advice, #45 suggested using NSIS but I don't familiar with these tools and also heard Windows 10+ changes its way to manage file association. I'm not too keen to deal with the registry mess so I suggest you use the workaround to associate it manually for now, it's planned to be improved though (please track this issue in #13 and #45). Sorry about the inconvenient :/
