### ISSUE TITLE
Windows MSVC 编译器下使用 QMake 构建，则需要链接 user32.lib 才能正常构建

### ISSUE THREAD

**Issue by libaineu2004** [BLumia/pineapple-pictures#58]
源文件framelesswindow.cpp，需要依赖库user32.lib
#ifdef _WIN32
#include <windows.h>
**#pragma comment(lib, "user32.lib")**
#endif // _WIN32

本人测试，发现编译通不过，但是加上这句话就好了。
#pragma comment(lib, "user32.lib")

**Comment by BLumia** [comment]
你是使用的 CMake 的方式构建的吗？

`#pragma comment` 是 msvc 特有的 macro，我在 CMake 确实没特别指定这个库的链接...

**Comment by libaineu2004** [comment]
> 你是使用的 CMake 的方式使用 MSVC 工具链构建的吗？
> 
> `#pragma comment` 是 MSVC 特有的 macro，我在 CMake 确实没特别指定这个库的链接...
> 
> edit: 查了一下，CMake 在 MSVC 下默认 `CMAKE_CXX_STANDARD_LIBRARIES` 变量中是包含 user32.lib 的，所以你是使用 qmake 构建的吗？如果是，切换到 CMake 构建也会有问题吗？

我是qmake编译的。你在源码新增#pragma comment(lib, "user32.lib")就好了。

**Comment by BLumia** [comment]
> > 你是使用的 CMake 的方式使用 MSVC 工具链构建的吗？
> > `#pragma comment` 是 MSVC 特有的 macro，我在 CMake 确实没特别指定这个库的链接...
> > edit: 查了一下，CMake 在 MSVC 下默认 `CMAKE_CXX_STANDARD_LIBRARIES` 变量中是包含 user32.lib 的，所以你是使用 qmake 构建的吗？如果是，切换到 CMake 构建也会有问题吗？
> 
> 我是qmake编译的。你在源码新增#pragma comment(lib, "user32.lib")就好了。

如上所说，`#pragma comment(lib, "user32.lib")` 是 MSVC 特有的宏，对于跨平台程序，这个不适合直接写进去。

你可以尝试下使用 CMake 构建吗？理论上，使用 CMake 的话，不需要任何修改就可以完成编译。

**Comment by libaineu2004** [comment]
> #ifdef _WIN32
> #include <windows.h>
> **#pragma comment(lib, "user32.lib")**
> #endif // _WIN32

有宏定义#ifdef _WIN32在控制，怕啥跨平台？
#ifdef _WIN32
#include <windows.h>
#pragma comment(lib, "user32.lib")
#endif // _WIN32
我平时开发只用qmake

**Comment by BLumia** [comment]
> 有宏定义#ifdef _WIN32在控制，怕啥跨平台？

比如我使用 MinGW，并不需要主动链接 user32.lib。我知道也可以同样的形式判断是否是 MinGW，但我不觉得这种做法很干净。

目前的 qmake 配置只是为了最初 Qt6 支持的简单测试而预留的，后续也会移除。我比较介意在代码（而不是构建脚本）里写编译器限定的特性。

**Comment by libaineu2004** [comment]
> > 有宏定义#ifdef _WIN32在控制，怕啥跨平台？
> 
> 比如我使用 MinGW，并不需要主动链接 user32.lib。我知道也可以同样的形式判断是否是 MinGW，但我不觉得这种做法很干净。
> 
> 目前的 qmake 配置只是为了最初 Qt6 支持的简单测试而预留的，后续也会移除。我比较介意在代码（而不是构建脚本）里写编译器限定的特性。

能加就加一下，不能加也请readme文档说明一下，不然我们直接拿到这套源码，qmake一编译就报错。也不好。

**Comment by BLumia** [comment]
> 能加就加一下，不能加也请readme文档说明一下，不然我们直接拿到这套源码，qmake一编译就报错。也不好。

我暂时没 MSVC + qmake 环境，随后找个环境测试下，然后看看要不要更新下 .pro 文件。感谢反馈。

**Comment by BLumia** [comment]
哦对了，作为补充：qmake 构建的版本是完全没包含 EXIV2 支持的，所以不能读取图片内的 EXIF 和 XMP 等元信息。如果希望有这类支持的话，还是建议考虑切换到 CMake。

**Comment by libaineu2004** [comment]
> 哦对了，作为补充：qmake 构建的版本是完全没包含 EXIV2 支持的，所以不能读取图片内的 EXIF 和 XMP 等元信息。如果希望有这类支持的话，还是建议考虑切换到 CMake。

好的。建议这条信息在readme说明一下。谢谢！

**Comment by BLumia** [comment]
其实原本 README 压根没提到 QMake，所以现在 README 补充了关于 QMake 不受此项目直接支持的描述。

至于问题本身，已更新 .pro 文件来链接对应的库，且添加了一个 CI 来检查这个问题。
