### ISSUE TITLE
启动速度优化

### ISSUE THREAD

**Issue by cei8** [BLumia/pineapple-pictures#67]
除了打开图片的速度略卡，其他都好。优化好启动速度，是理想中的看图软件。

**Comment by BLumia** [comment]
其实你删掉一部分图像格式支持插件的话（在 `imageformats` 目录下），应该会更快一些。要再提速的话就得改异步加载（先出窗口再出图片）以及别的地方了。

这个问题恐怕没有比较好的衡量标准来判断怎么算解决（其实 Linux/KDE 下是秒开的，Windows 在有 superfetch 的情况下，除了首次启动外应该也可以接受），我先关闭掉吧。

尽管 Windows 下的启动速度我也不是很满意，但目前也算能接受。曾经考虑过提供一个常驻托盘的方案以便快速启动，但感觉太怪了，觉得是很不干净的处理方式，所以最终没选这种方案。当然如果你（或者别的有兴趣的人）有更好的方案的话也欢迎讨论。

感谢支持~

**Comment by BLumia** [comment]
之前的回复没提到静态构建。静态构建其实也可以比较大的提升启动速度（减少了先找/加载 DLL 的时间）。最近刚好在实验相关的支持，我在这里也提供一个预编译好的静态版本，来供尝试：

[ppic-static-experimental-version.zip](https://github.com/BLumia/pineapple-pictures/files/9943874/ppic-static-experimental-version.zip)

注意：这是实验性的版本，这个版本中不包含由 EXIV2 提供的图像元信息支持（也就是说有 EXIV、XMP 之类的标签的话是不会在属性里显示的），图像格式也只包含了最基础的格式额外加上 PSD。

因为是实验性支持，所以我不确定后续的发布里就一定会使用或提供静态版，当然也欢迎相关的反馈 :)
