### ISSUE TITLE
license contradiction

### ISSUE THREAD

**Issue by sudipm-mukherjee** [BLumia/pineapple-pictures#8]
The project is released under MIT license but the file `dist/appstream/net.blumia.pineapple-pictures.appdata.xml` says `<project_license>GPL-3.0+</project_license>` which is contradicting the main project license and is confusing. Can you please check and fix it..

**Comment by BLumia** [comment]
Oops, sorry I did copy-paste the xml structure of the appdata.xml from other project but forget to change the license field. Will be fixed in the next commit.

Thanks for let me know!

**Comment by BLumia** [comment]
Should be fixed in 7e78257 :)

Feel free to let me know if there are still anything wrong, thanks!
