### ISSUE TITLE
功能建议：在系统任务栏处显示对应的图片名称

### ISSUE THREAD

**Issue by blue2018** [BLumia/pineapple-pictures#84]
希望程序在系统任务栏处显示对应的图片名称，否则打开多张图片时，不好辨认需要查看的图片，谢谢

**Comment by BLumia** [comment]
在 https://github.com/BLumia/pineapple-pictures/commit/6a992f4c1fd88232c66756d92b9641890d946354 这个 commit 中增加了这个特性。可以下载 CI 版本尝试了。功能也会涵盖在下次版本发布里。
