### ISSUE TITLE
功能建议：暂停 gif 或 gif 逐帧播放

### ISSUE THREAD

**Issue by J-11** [BLumia/pineapple-pictures#85]
1，希望支持暂停gif，或者显示gif帧数，如果能逐帧播放gif就更好了。
2，图片放大超过窗口时，窗口就不能移动了，希望窗口上边留出一条区域用来移动窗口。

这个软件我太喜欢了，放大不加模糊实在是太难得，谢谢大佬。

**Comment by BLumia** [comment]
> 希望支持暂停gif ... 如果能逐帧播放gif就更好了。

有这个想法，不过因为自己没这种使用场景所以一直懒得写，可能回头闲了会加上吧。

> 或者显示gif帧数

这个是有的，应用内的属性对话框，是动图（不限于 gif）的话会显示总帧数。

> 图片放大超过窗口时，窗口就不能移动了，希望窗口上边留出一条区域用来移动窗口。

可能不是很直观，不过下方按钮区域的边缘其实可以用来拖动（当前的预期用法）。其实本来考虑要不要加个假的标题栏，但自己不是很喜欢标题栏这种解决方案 😂

**Comment by J-11** [comment]
感谢回复，期待后续更新(๑•̀ㅂ•́)و✧
