### ISSUE TITLE
能否增加一键直接文件关联的功能？

### ISSUE THREAD

**Issue by hanxuyuan** [BLumia/pineapple-pictures#90]
我有个别大图，试了好几个比较知名的看图软件，都会失败，唯独你成功了。
而且半透明的背景和无边框模式我特别特别的喜欢！非常想作为默认看图软件。
但是似乎不能主动进行文件关联，貌似只能通过鼠标右键改变文件打开方式来曲线救国？

能否在软件内直接添加一键文件关联功能？

**Comment by BLumia** [comment]
和 https://github.com/BLumia/pineapple-pictures/issues/13 重复。

有计划，但一直鸽着没做，短期内也没打算去做。主要这个问题是 Windows 仅有而我又很懒得研究 Windows 的文件关联机制现在是什么样子的（XP，7+，10+ 的行为似乎都不一样）...

目前还是建议手动挨个关联吧，可以去上面提到的 issue 的右侧点个 Subscribe，后续如果真做了的话会在那个 issue 里更新状态。
