### ISSUE TITLE
——作者你好，感谢你研发软件：WIN7系统图片无法关联使用这软件默认打开

### ISSUE THREAD

**Issue by gemkeeper** [BLumia/pineapple-pictures#95]
作者朋友你好：
    我是中国的一个用户，
    您的这个软件做的相当好，耗费内存很小，切换速度也很快，
    看得出您是非常用心研发了，对你表达感谢、赞美和钦佩！
    我反映1个情况：
我的WIN7-64位操作系统，日常使用：
最新、最先进的的3种类型的.jxl(JPEG XL)   .avif   .webp2  以及.webp  格式图片，
和经典的.png .jpg  .gif 三种图片格式，

但是现在的  Pineapple Pictures Pineapple Pictures 无法 关联系统 的图片类型 设置为 双击鼠标左键 默认使用 这软件 打开，
在图片文件上 鼠标右键 选择 打开方式，选择  Pineapple Pictures Pineapple Pictures 的文件夹主程序，依然无效，
以后版本可否改进成：可以 顺利关联，设置为 鼠标左键双击图片 默认使用本软件打开？

**Comment by BLumia** [comment]
你好，我讲中文所以我就用中文答复了 :)

当你在 Windows 7 下，手动关联图片时，具体“无效”指的是怎样的情况呢？是指进行关联后双击打开了程序但没有看到你所双击的图片吗？或者是发现双击时压根没打开这个程序？

由于我没有 Windows 7 设备，所以不便测试，但此应用是普通的 Win 32 可执行程序，接受图片文件路径作为参数的形式来打开文件，所以理论上应当是可以使用的才对，并不应当存在无效的情况。

**Comment by BLumia** [comment]
我找了个有 Win 7 环境的朋友进行了测试，并不存在你所说的问题。

由于已一周多没有更多信息提供，我就关掉这个 issue 了。如果有信息补充的话，在补充且确认可复现问题后可以再打开此 issue。

**Comment by gemkeeper** [comment]
如下3图所示，下载pineapple-pictures-0.7.1-Windows-x86_64.zip后，解压到C区下，
复制文件目录C:\0\pineapple-pictures-0.7.1-Windows-x86_64\
选择任一图片，鼠标右键选 打开方式（H），
选择默认程序，把复制的目录路径C:\0\pineapple-pictures-0.7.1-Windows-x86_64粘贴到弹出的选择程序框里，
点选ppic.exe程序，点右下角 打开（O）
这时候 打开方式 里，推荐的程序 栏里，和 其他程序栏 里，全都找不到 ppix.exe的主程序图片和名称，
——我是想把ppix.exe设置为 我电脑上图片的默认打开方式，
这样以后只需要鼠标左键双击图片，即可自动调用ppix.exe打开图片，
但是现在无法做到

![1](https://github.com/BLumia/pineapple-pictures/assets/90263018/aa7eae1e-05cb-40cb-beae-583f09dd350e)
![2](https://github.com/BLumia/pineapple-pictures/assets/90263018/95574ff0-aead-4116-a1b5-5b6cef1875f3)
![3](https://github.com/BLumia/pineapple-pictures/assets/90263018/e9b072ea-8587-40d9-9718-c88ae18ceeb2)

**Comment by BLumia** [comment]
https://github.com/BLumia/pineapple-pictures/assets/10095765/8a5bb515-0d9c-43dd-aeff-d05f49b43e15

如上是在 Windows 7 `cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso` 镜像安装的虚拟机中，从崭新安装完毕的虚拟机，通过从宿主机开启共享文件夹获得 `pineapple-pictures-0.7.1-Windows-x86_64.zip` 与一个测试用的 GIF 图片文件，然后手动进行解压和文件关联，直至最后开启文件的全过程。

可见，此应用可以按预期行为工作，我无法复现你所描述的问题。

**Comment by gemkeeper** [comment]
这真是奇了个鬼了，我的系统是正常的win7-64，一直用360自动打组各种补丁组件，
如果是因为缺少某种组件而导致这种情况，却也不知道究竟是缺少哪个组件导致这种情况，
挺好的一个软件，却因为无法关联成默认软件，导致无法使用，实在太扫兴了。
